### ISSUE TITLE
Missing checkpoint (swin-large_upernet_unified_512x512/end2end.pt)

### ISSUE THREAD

**Issue by kopetri** [owenzlz/PAL4VST#3]
Hello, 

the url to the checkpoint: ([swin-large_upernet_unified_512x512](https://drive.google.com/file/d/1alICAkY8sjr-gwWknAEQjIKDkdPUPyKd/view?usp=sharing)) is not available.

Can fix the link please?

thx!

**Comment by owenzlz** [comment]
Hi, are you able to download from here: [https://drive.google.com/file/d/1bGjEKquWa4cZJ6v52NoRfViwKK15U7vd/view](https://drive.google.com/file/d/1bGjEKquWa4cZJ6v52NoRfViwKK15U7vd/view)?

I checked my link on the repo, and it was working. I am not sure where did you find the above link? Thanks!

**Comment by eneller** [comment]
the URL can be found in https://github.com/owenzlz/PAL4VST/blob/5c26feab93fa439a07c68efa0b20297ac3dd1b79/README.md?plain=1#L75, working version here: https://github.com/owenzlz/PAL4VST/blob/5c26feab93fa439a07c68efa0b20297ac3dd1b79/README.md?plain=1#L117

**Comment by kopetri** [comment]
working link found
